# Site settings
title: slowlytime
email: help@slowlytime.com
description: ""
baseurl: ""
url: "http://slowlytime.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
